# ==============================================================================
# Author: Devin A. King, PhD
#   Translational Neuroimmunology Research Center (TNRC) | Chitnis Lab
#   Mass General Brigham
#   Harvard Medical School
#
# Updated: 7-25-2026
#
# scDRS step 01 - prepare the two inputs the command-line steps need
#
#   (a) Seurat object -> .h5ad, for `scdrs compute-score`
#   (b) GWAS summary statistics -> MAGMA p-value file, for `magma`
#
#
# Inputs : R/pbmc_final.RDS          (whole-PBMC atlas)
#          R/B_clean.RDS             (B-cell object)
#          scdrs/ref/MS.final.txt    (MS GWAS summary statistics, not distributed)
# Outputs: scdrs/work/ms_pbmc.h5ad
#          scdrs/work/ms_bcells.h5ad
#          scdrs/work/MS.final.magma.tsv
# ==============================================================================

setwd("C:/Users/devin/Desktop/rrms")

source("R/packages.R")

if (!requireNamespace("scCustomize", quietly = TRUE))
  stop("scCustomize is required for the h5ad export: install.packages('scCustomize')")

OBJ_DIR  <- "R"
WORK_DIR <- "scdrs/work"
REF_DIR  <- "scdrs/ref"
dir.create(WORK_DIR, showWarnings = FALSE, recursive = TRUE)


# ==============================================================================
# (a) Seurat -> h5ad
# ==============================================================================
# scDRS reads raw counts from an AnnData object. Seurat v5 assays do not export
# cleanly, so the RNA assay is converted back to a v3 Assay first, and the
# imputed-ADT assay is dropped

export_h5ad <- function(seu, file_name, dir = WORK_DIR) {
  to_export <- seu
  Seurat::DefaultAssay(to_export) <- "RNA"
  if ("impADT" %in% Seurat::Assays(to_export)) to_export[["impADT"]] <- NULL

  assayv3 <- as(to_export[["RNA"]], "Assay")
  stopifnot(identical(colnames(assayv3), colnames(to_export)))
  to_export[["RNA"]] <- assayv3

  scCustomize::as.anndata(
    x               = to_export,
    file_path       = dir,
    file_name       = paste0(file_name, ".h5ad"),
    assay           = "RNA",
    main_layer      = "counts",
    other_layers    = NULL,
    transer_dimreduc = FALSE,     # (sic - argument is spelled this way upstream)
    verbose         = TRUE
  )
  message("wrote ", file.path(dir, paste0(file_name, ".h5ad")))
}

pbmc <- readRDS(file.path(OBJ_DIR, "pbmc_final.RDS"))
export_h5ad(pbmc, "ms_pbmc")
rm(pbmc); invisible(gc(FALSE))

B <- readRDS(file.path(OBJ_DIR, "B_clean.RDS"))
export_h5ad(B, "ms_bcells")
rm(B); invisible(gc(FALSE))


# ==============================================================================
# (b) GWAS summary statistics -> MAGMA p-value file
# ==============================================================================
# MAGMA wants a plain table with a SNP id column and a p-value column. The
# per-SNP sample size is carried through as N; the gene-analysis step in
# 02_magma.sh passes N = 41505 explicitly.
#
# MS.final.txt holds MS GWAS summary statistics generated by the International
# Multiple Sclerosis Genetics Consortium (https://doi.org/10.1126/science.aav7188)
# and obtained from the consortium. They are not redistributed with this
# repository; request them directly from the IMSGC (https://imsgc.net/).
# The derived gene set is provided at scdrs/MS.gs (see scdrs/README.md).

gwas_file <- file.path(REF_DIR, "MS.final.txt")
if (!file.exists(gwas_file)) {
  warning("GWAS summary statistics not found at ", gwas_file,
          " - skipping the MAGMA input step. See scdrs/README.md.")
} else {
  gwas <- data.table::fread(gwas_file)
  stopifnot(all(c("SNP", "CHR", "BP", "A1", "A2", "P") %in% names(gwas)))
  print(summary(gwas$P))

  out <- gwas[, c("SNP", "P", "N")]
  write.table(out, file.path(WORK_DIR, "MS.final.magma.tsv"),
              sep = '\t', quote = FALSE, row.names = FALSE)
  message("wrote ", file.path(WORK_DIR, "MS.final.magma.tsv"),
          "  (", nrow(out), " SNPs)")
}
